require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EditablePagesController do

  # This should return the minimal set of attributes required to create a valid
  # EditablePage. As you add validations to EditablePage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "window_title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EditablePagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all editable_pages as @editable_pages" do
      editable_page = EditablePage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:editable_pages).should eq([editable_page])
    end
  end

  describe "GET show" do
    it "assigns the requested editable_page as @editable_page" do
      editable_page = EditablePage.create! valid_attributes
      get :show, {:id => editable_page.to_param}, valid_session
      assigns(:editable_page).should eq(editable_page)
    end
  end

  describe "GET new" do
    it "assigns a new editable_page as @editable_page" do
      get :new, {}, valid_session
      assigns(:editable_page).should be_a_new(EditablePage)
    end
  end

  describe "GET edit" do
    it "assigns the requested editable_page as @editable_page" do
      editable_page = EditablePage.create! valid_attributes
      get :edit, {:id => editable_page.to_param}, valid_session
      assigns(:editable_page).should eq(editable_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EditablePage" do
        expect {
          post :create, {:editable_page => valid_attributes}, valid_session
        }.to change(EditablePage, :count).by(1)
      end

      it "assigns a newly created editable_page as @editable_page" do
        post :create, {:editable_page => valid_attributes}, valid_session
        assigns(:editable_page).should be_a(EditablePage)
        assigns(:editable_page).should be_persisted
      end

      it "redirects to the created editable_page" do
        post :create, {:editable_page => valid_attributes}, valid_session
        response.should redirect_to(EditablePage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved editable_page as @editable_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        EditablePage.any_instance.stub(:save).and_return(false)
        post :create, {:editable_page => { "window_title" => "invalid value" }}, valid_session
        assigns(:editable_page).should be_a_new(EditablePage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EditablePage.any_instance.stub(:save).and_return(false)
        post :create, {:editable_page => { "window_title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested editable_page" do
        editable_page = EditablePage.create! valid_attributes
        # Assuming there are no other editable_pages in the database, this
        # specifies that the EditablePage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EditablePage.any_instance.should_receive(:update_attributes).with({ "window_title" => "MyString" })
        put :update, {:id => editable_page.to_param, :editable_page => { "window_title" => "MyString" }}, valid_session
      end

      it "assigns the requested editable_page as @editable_page" do
        editable_page = EditablePage.create! valid_attributes
        put :update, {:id => editable_page.to_param, :editable_page => valid_attributes}, valid_session
        assigns(:editable_page).should eq(editable_page)
      end

      it "redirects to the editable_page" do
        editable_page = EditablePage.create! valid_attributes
        put :update, {:id => editable_page.to_param, :editable_page => valid_attributes}, valid_session
        response.should redirect_to(editable_page)
      end
    end

    describe "with invalid params" do
      it "assigns the editable_page as @editable_page" do
        editable_page = EditablePage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EditablePage.any_instance.stub(:save).and_return(false)
        put :update, {:id => editable_page.to_param, :editable_page => { "window_title" => "invalid value" }}, valid_session
        assigns(:editable_page).should eq(editable_page)
      end

      it "re-renders the 'edit' template" do
        editable_page = EditablePage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EditablePage.any_instance.stub(:save).and_return(false)
        put :update, {:id => editable_page.to_param, :editable_page => { "window_title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested editable_page" do
      editable_page = EditablePage.create! valid_attributes
      expect {
        delete :destroy, {:id => editable_page.to_param}, valid_session
      }.to change(EditablePage, :count).by(-1)
    end

    it "redirects to the editable_pages list" do
      editable_page = EditablePage.create! valid_attributes
      delete :destroy, {:id => editable_page.to_param}, valid_session
      response.should redirect_to(editable_pages_url)
    end
  end

end
